//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.request;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ControllerRole.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ControllerRole">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="primary"/>
 *     &lt;enumeration value="backup"/>
 *     &lt;enumeration value="monitor"/>
 *     &lt;enumeration value="master"/>
 *     &lt;enumeration value="equal"/>
 *     &lt;enumeration value="slave"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ControllerRole", namespace = "http://www.geni.net/resources/rspec/ext/openflow/4")
@XmlEnum
public enum ControllerRole {

    @XmlEnumValue("primary")
    PRIMARY("primary"),
    @XmlEnumValue("backup")
    BACKUP("backup"),
    @XmlEnumValue("monitor")
    MONITOR("monitor"),
    @XmlEnumValue("master")
    MASTER("master"),
    @XmlEnumValue("equal")
    EQUAL("equal"),
    @XmlEnumValue("slave")
    SLAVE("slave");
    private final String value;

    ControllerRole(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ControllerRole fromValue(String v) {
        for (ControllerRole c: ControllerRole.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
