//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.request;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HopContent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HopContent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aggregateIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="nodeIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="portIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linkIdRef" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/stitch/2/}aggregate" minOccurs="0"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/stitch/2/}port" minOccurs="0"/>
 *         &lt;element name="nextHop" type="{http://www.geni.net/resources/rspec/ext/stitch/2/}NextHopContent" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HopContent", namespace = "http://www.geni.net/resources/rspec/ext/stitch/2/", propOrder = {
    "aggregateIdRef",
    "nodeIdRef",
    "portIdRef",
    "linkIdRef",
    "aggregate",
    "port",
    "nextHop"
})
public class HopContent {

    protected String aggregateIdRef;
    protected String nodeIdRef;
    protected String portIdRef;
    protected String linkIdRef;
    protected AggregateContent aggregate;
    protected PortContent port;
    protected List<NextHopContent> nextHop;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the aggregateIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggregateIdRef() {
        return aggregateIdRef;
    }

    /**
     * Sets the value of the aggregateIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggregateIdRef(String value) {
        this.aggregateIdRef = value;
    }

    /**
     * Gets the value of the nodeIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeIdRef() {
        return nodeIdRef;
    }

    /**
     * Sets the value of the nodeIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeIdRef(String value) {
        this.nodeIdRef = value;
    }

    /**
     * Gets the value of the portIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortIdRef() {
        return portIdRef;
    }

    /**
     * Sets the value of the portIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortIdRef(String value) {
        this.portIdRef = value;
    }

    /**
     * Gets the value of the linkIdRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkIdRef() {
        return linkIdRef;
    }

    /**
     * Sets the value of the linkIdRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkIdRef(String value) {
        this.linkIdRef = value;
    }

    /**
     * Gets the value of the aggregate property.
     * 
     * @return
     *     possible object is
     *     {@link AggregateContent }
     *     
     */
    public AggregateContent getAggregate() {
        return aggregate;
    }

    /**
     * Sets the value of the aggregate property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregateContent }
     *     
     */
    public void setAggregate(AggregateContent value) {
        this.aggregate = value;
    }

    /**
     * Gets the value of the port property.
     * 
     * @return
     *     possible object is
     *     {@link PortContent }
     *     
     */
    public PortContent getPort() {
        return port;
    }

    /**
     * Sets the value of the port property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortContent }
     *     
     */
    public void setPort(PortContent value) {
        this.port = value;
    }

    /**
     * Gets the value of the nextHop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nextHop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNextHop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NextHopContent }
     * 
     * 
     */
    public List<NextHopContent> getNextHop() {
        if (nextHop == null) {
            nextHop = new ArrayList<NextHopContent>();
        }
        return this.nextHop;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

}
