//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchContents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}use-group"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}packet"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchContents", namespace = "http://www.geni.net/resources/rspec/ext/openflow/4", propOrder = {
    "useGroup",
    "packet"
})
public class MatchContents {

    @XmlElement(name = "use-group", required = true)
    protected UseGroup useGroup;
    @XmlElement(required = true)
    protected PacketContents packet;

    /**
     * Gets the value of the useGroup property.
     * 
     * @return
     *     possible object is
     *     {@link UseGroup }
     *     
     */
    public UseGroup getUseGroup() {
        return useGroup;
    }

    /**
     * Sets the value of the useGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseGroup }
     *     
     */
    public void setUseGroup(UseGroup value) {
        this.useGroup = value;
    }

    /**
     * Gets the value of the packet property.
     * 
     * @return
     *     possible object is
     *     {@link PacketContents }
     *     
     */
    public PacketContents getPacket() {
        return packet;
    }

    /**
     * Sets the value of the packet property.
     * 
     * @param value
     *     allowed object is
     *     {@link PacketContents }
     *     
     */
    public void setPacket(PacketContents value) {
        this.packet = value;
    }

}
