//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PacketContents complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PacketContents">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}dl_vlan"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}dl_type"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}nw_dst"/>
 *         &lt;element ref="{http://www.geni.net/resources/rspec/ext/openflow/4}nw_src"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PacketContents", namespace = "http://www.geni.net/resources/rspec/ext/openflow/4", propOrder = {
    "dlVlan",
    "dlType",
    "nwDst",
    "nwSrc"
})
public class PacketContents {

    @XmlElement(name = "dl_vlan", required = true)
    protected DlVlan dlVlan;
    @XmlElement(name = "dl_type", required = true)
    protected DlType dlType;
    @XmlElement(name = "nw_dst", required = true)
    protected NwDst nwDst;
    @XmlElement(name = "nw_src", required = true)
    protected NwSrc nwSrc;

    /**
     * Gets the value of the dlVlan property.
     * 
     * @return
     *     possible object is
     *     {@link DlVlan }
     *     
     */
    public DlVlan getDlVlan() {
        return dlVlan;
    }

    /**
     * Sets the value of the dlVlan property.
     * 
     * @param value
     *     allowed object is
     *     {@link DlVlan }
     *     
     */
    public void setDlVlan(DlVlan value) {
        this.dlVlan = value;
    }

    /**
     * Gets the value of the dlType property.
     * 
     * @return
     *     possible object is
     *     {@link DlType }
     *     
     */
    public DlType getDlType() {
        return dlType;
    }

    /**
     * Sets the value of the dlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DlType }
     *     
     */
    public void setDlType(DlType value) {
        this.dlType = value;
    }

    /**
     * Gets the value of the nwDst property.
     * 
     * @return
     *     possible object is
     *     {@link NwDst }
     *     
     */
    public NwDst getNwDst() {
        return nwDst;
    }

    /**
     * Sets the value of the nwDst property.
     * 
     * @param value
     *     allowed object is
     *     {@link NwDst }
     *     
     */
    public void setNwDst(NwDst value) {
        this.nwDst = value;
    }

    /**
     * Gets the value of the nwSrc property.
     * 
     * @return
     *     possible object is
     *     {@link NwSrc }
     *     
     */
    public NwSrc getNwSrc() {
        return nwSrc;
    }

    /**
     * Sets the value of the nwSrc property.
     * 
     * @param value
     *     allowed object is
     *     {@link NwSrc }
     *     
     */
    public void setNwSrc(NwSrc value) {
        this.nwSrc = value;
    }

}
