//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.geni.net/resources/rspec/3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package info.openmultinet.ontology.translators.geni.jaxb.request;
