//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:12 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SwitchingCapabilitySpecificInfo_Lsc complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwitchingCapabilitySpecificInfo_Lsc">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="capability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wavelengthSpacing" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wavelengthRangeAvailability" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="suggestedWavelengthRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="wavelengthTranslation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwitchingCapabilitySpecificInfo_Lsc", namespace = "http://www.geni.net/resources/rspec/ext/stitch/2/", propOrder = {
    "capability",
    "wavelengthSpacing",
    "wavelengthRangeAvailability",
    "suggestedWavelengthRange",
    "wavelengthTranslation"
})
public class SwitchingCapabilitySpecificInfoLsc {

    protected String capability;
    protected String wavelengthSpacing;
    protected String wavelengthRangeAvailability;
    protected String suggestedWavelengthRange;
    protected String wavelengthTranslation;

    /**
     * Gets the value of the capability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapability() {
        return capability;
    }

    /**
     * Sets the value of the capability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapability(String value) {
        this.capability = value;
    }

    /**
     * Gets the value of the wavelengthSpacing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWavelengthSpacing() {
        return wavelengthSpacing;
    }

    /**
     * Sets the value of the wavelengthSpacing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWavelengthSpacing(String value) {
        this.wavelengthSpacing = value;
    }

    /**
     * Gets the value of the wavelengthRangeAvailability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWavelengthRangeAvailability() {
        return wavelengthRangeAvailability;
    }

    /**
     * Sets the value of the wavelengthRangeAvailability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWavelengthRangeAvailability(String value) {
        this.wavelengthRangeAvailability = value;
    }

    /**
     * Gets the value of the suggestedWavelengthRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSuggestedWavelengthRange() {
        return suggestedWavelengthRange;
    }

    /**
     * Sets the value of the suggestedWavelengthRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSuggestedWavelengthRange(String value) {
        this.suggestedWavelengthRange = value;
    }

    /**
     * Gets the value of the wavelengthTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWavelengthTranslation() {
        return wavelengthTranslation;
    }

    /**
     * Sets the value of the wavelengthTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWavelengthTranslation(String value) {
        this.wavelengthTranslation = value;
    }

}
