PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix f4f: <https://github.com/w3c/omn/blob/master/omnlib/ontologies/omn#>
DESCRIBE ?subject ?object
	WHERE { ?subject rdf:type f4f:Testbed }
