PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix novi: <http://fp7-novi.eu/im.owl#>
prefix omn: <https://github.com/w3c/omn/blob/master/omnlib/ontologies/omn#> 

SELECT ?resource ?start ?stop WHERE{
    ?resource omn:partOfGroup ?reservation .
    ?reservation novi:startTime ?start ;
                 novi:endTime ?stop .
    FILTER(?start > "2010-01-19T16:00:00Z"^^xsd:dateTime )
}
