/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/robynloughnane/git/omnnew/playground-rspecs-ontology/omnlib/import/http.ttl 
 * @author Auto-generated by schemagen on 01 Sep 2015 13:43 
 */
public class Http {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2006/http#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>An absolute path used as request URI</p> */
    public static final OntProperty abs_path = m_model.createOntProperty( "http://www.w3.org/2006/http#abs_path" );
    
    /** <p>An absolute request URI</p> */
    public static final OntProperty absoluteURI = m_model.createOntProperty( "http://www.w3.org/2006/http#absoluteURI" );
    
    /** <p>An authority used as request URI</p> */
    public static final OntProperty authority = m_model.createOntProperty( "http://www.w3.org/2006/http#authority" );
    
    /** <p>The HTTP entity body</p> */
    public static final OntProperty body = m_model.createOntProperty( "http://www.w3.org/2006/http#body" );
    
    /** <p>An HTTP Connection authority</p> */
    public static final OntProperty connectionAuthority = m_model.createOntProperty( "http://www.w3.org/2006/http#connectionAuthority" );
    
    /** <p>Has an element name</p> */
    public static final OntProperty elementName = m_model.createOntProperty( "http://www.w3.org/2006/http#elementName" );
    
    /** <p>Has an element value</p> */
    public static final OntProperty elementValue = m_model.createOntProperty( "http://www.w3.org/2006/http#elementValue" );
    
    /** <p>Has a field name</p> */
    public static final OntProperty fieldName = m_model.createOntProperty( "http://www.w3.org/2006/http#fieldName" );
    
    /** <p>Has a field value</p> */
    public static final OntProperty fieldValue = m_model.createOntProperty( "http://www.w3.org/2006/http#fieldValue" );
    
    /** <p>Has a header</p> */
    public static final OntProperty header = m_model.createOntProperty( "http://www.w3.org/2006/http#header" );
    
    /** <p>Has a parameter</p> */
    public static final OntProperty param = m_model.createOntProperty( "http://www.w3.org/2006/http#param" );
    
    /** <p>Has a parameter name</p> */
    public static final OntProperty paramName = m_model.createOntProperty( "http://www.w3.org/2006/http#paramName" );
    
    /** <p>Has a parameter value</p> */
    public static final OntProperty paramValue = m_model.createOntProperty( "http://www.w3.org/2006/http#paramValue" );
    
    /** <p>Has an HTTP request</p> */
    public static final OntProperty request = m_model.createOntProperty( "http://www.w3.org/2006/http#request" );
    
    /** <p>Has an HTTP request URI</p> */
    public static final OntProperty requestURI = m_model.createOntProperty( "http://www.w3.org/2006/http#requestURI" );
    
    /** <p>Has an HTTP response</p> */
    public static final OntProperty response = m_model.createOntProperty( "http://www.w3.org/2006/http#response" );
    
    /** <p>Has an HTTP response code</p> */
    public static final OntProperty responseCode = m_model.createOntProperty( "http://www.w3.org/2006/http#responseCode" );
    
    /** <p>The HTTP version</p> */
    public static final OntProperty version = m_model.createOntProperty( "http://www.w3.org/2006/http#version" );
    
    /** <p>The CONNECT request</p> */
    public static final OntClass ConnectRequest = m_model.createClass( "http://www.w3.org/2006/http#ConnectRequest" );
    
    /** <p>An HTTP connection</p> */
    public static final OntClass Connection = m_model.createClass( "http://www.w3.org/2006/http#Connection" );
    
    /** <p>The DELETE request</p> */
    public static final OntClass DeleteRequest = m_model.createClass( "http://www.w3.org/2006/http#DeleteRequest" );
    
    /** <p>The GET request</p> */
    public static final OntClass GetRequest = m_model.createClass( "http://www.w3.org/2006/http#GetRequest" );
    
    /** <p>The HEAD request</p> */
    public static final OntClass HeadRequest = m_model.createClass( "http://www.w3.org/2006/http#HeadRequest" );
    
    /** <p>An element of a comma-separated list in a field value</p> */
    public static final OntClass HeaderElement = m_model.createClass( "http://www.w3.org/2006/http#HeaderElement" );
    
    public static final OntClass HeaderName = m_model.createClass( "http://www.w3.org/2006/http#HeaderName" );
    
    /** <p>A message header according to section 4.2 of HTTP 1.1</p> */
    public static final OntClass MessageHeader = m_model.createClass( "http://www.w3.org/2006/http#MessageHeader" );
    
    /** <p>New HTTP Response Code. If you want to define new header names, subclass this 
     *  stub.</p>
     */
    public static final OntClass NewResponseCode = m_model.createClass( "http://www.w3.org/2006/http#NewResponseCode" );
    
    /** <p>The OPTIONS request</p> */
    public static final OntClass OptionsRequest = m_model.createClass( "http://www.w3.org/2006/http#OptionsRequest" );
    
    /** <p>A parameter for a header element</p> */
    public static final OntClass Param = m_model.createClass( "http://www.w3.org/2006/http#Param" );
    
    /** <p>The POST request</p> */
    public static final OntClass PostRequest = m_model.createClass( "http://www.w3.org/2006/http#PostRequest" );
    
    /** <p>The PUT request</p> */
    public static final OntClass PutRequest = m_model.createClass( "http://www.w3.org/2006/http#PutRequest" );
    
    /** <p>An HTTP request</p> */
    public static final OntClass Request = m_model.createClass( "http://www.w3.org/2006/http#Request" );
    
    /** <p>The HTTP request URI</p> */
    public static final OntClass RequestURI = m_model.createClass( "http://www.w3.org/2006/http#RequestURI" );
    
    /** <p>The HTTP Response</p> */
    public static final OntClass Response = m_model.createClass( "http://www.w3.org/2006/http#Response" );
    
    /** <p>The HTTP Response Code</p> */
    public static final OntClass ResponseCode = m_model.createClass( "http://www.w3.org/2006/http#ResponseCode" );
    
    /** <p>The TRACE request</p> */
    public static final OntClass TraceRequest = m_model.createClass( "http://www.w3.org/2006/http#TraceRequest" );
    
}
