/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/robynloughnane/git/omnnew/playground-rspecs-ontology/omnlib/ontologies/omn-service.ttl 
 * @author Auto-generated by schemagen on 01 Sep 2015 13:57 
 */
public class Omn_service {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://open-multinet.info/ontology/omn-service#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "2015-04-29";
    
    /** <p>URI of OSMP monitoring service</p> */
    public static final ObjectProperty hasURI = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-service#hasURI" );
    
    /** <p>Login Service authentication type, e.g. 'ssh-keys'</p> */
    public static final DatatypeProperty authentication = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#authentication" );
    
    /** <p>Execute Service command</p> */
    public static final DatatypeProperty command = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#command" );
    
    /** <p>Login Service hostname</p> */
    public static final DatatypeProperty hostname = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#hostname" );
    
    /** <p>Install Service install path</p> */
    public static final DatatypeProperty installPath = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#installPath" );
    
    /** <p>Login Service port</p> */
    public static final DatatypeProperty port = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#port" );
    
    /** <p>post boot script text</p> */
    public static final DatatypeProperty postBootScriptText = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#postBootScriptText" );
    
    /** <p>post boot script type</p> */
    public static final DatatypeProperty postBootScriptType = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#postBootScriptType" );
    
    /** <p>Login Service public key</p> */
    public static final DatatypeProperty publickey = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#publickey" );
    
    /** <p>Execute Service shell</p> */
    public static final DatatypeProperty shell = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#shell" );
    
    /** <p>Install Service url</p> */
    public static final DatatypeProperty url = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#url" );
    
    /** <p>Login Service username</p> */
    public static final DatatypeProperty username = m_model.createDatatypeProperty( "http://open-multinet.info/ontology/omn-service#username" );
    
    /** <p>GENI Manifest RSpec v3: ExecuteServiceContents</p> */
    public static final OntClass ExecuteService = m_model.createClass( "http://open-multinet.info/ontology/omn-service#ExecuteService" );
    
    /** <p>GENI Manifest RSpec v3: InstallServiceContents</p> */
    public static final OntClass InstallService = m_model.createClass( "http://open-multinet.info/ontology/omn-service#InstallService" );
    
    /** <p>GENI Manifest RSpec v3: LoginServiceContents</p> */
    public static final OntClass LoginService = m_model.createClass( "http://open-multinet.info/ontology/omn-service#LoginService" );
    
    /** <p>GENI Manifest RSpec v3 extension: postBootScript</p> */
    public static final OntClass PostBootScript = m_model.createClass( "http://open-multinet.info/ontology/omn-service#PostBootScript" );
    
}
