//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.01 at 01:40:11 PM CEST 
//


package info.openmultinet.ontology.translators.geni.jaxb.advertisement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SwitchingCapabilityDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwitchingCapabilityDescriptor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="switchingcapType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="encodingType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="switchingCapabilitySpecificInfo" type="{http://www.geni.net/resources/rspec/ext/stitch/2/}SwitchingCapabilitySpecificInfo"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwitchingCapabilityDescriptor", namespace = "http://www.geni.net/resources/rspec/ext/stitch/2/", propOrder = {
    "switchingcapType",
    "encodingType",
    "switchingCapabilitySpecificInfo"
})
public class SwitchingCapabilityDescriptor {

    @XmlElement(required = true)
    protected String switchingcapType;
    @XmlElement(required = true)
    protected String encodingType;
    @XmlElement(required = true)
    protected SwitchingCapabilitySpecificInfo switchingCapabilitySpecificInfo;

    /**
     * Gets the value of the switchingcapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwitchingcapType() {
        return switchingcapType;
    }

    /**
     * Sets the value of the switchingcapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwitchingcapType(String value) {
        this.switchingcapType = value;
    }

    /**
     * Gets the value of the encodingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncodingType() {
        return encodingType;
    }

    /**
     * Sets the value of the encodingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncodingType(String value) {
        this.encodingType = value;
    }

    /**
     * Gets the value of the switchingCapabilitySpecificInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchingCapabilitySpecificInfo }
     *     
     */
    public SwitchingCapabilitySpecificInfo getSwitchingCapabilitySpecificInfo() {
        return switchingCapabilitySpecificInfo;
    }

    /**
     * Sets the value of the switchingCapabilitySpecificInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchingCapabilitySpecificInfo }
     *     
     */
    public void setSwitchingCapabilitySpecificInfo(SwitchingCapabilitySpecificInfo value) {
        this.switchingCapabilitySpecificInfo = value;
    }

}
