/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from src/main/resources/omn-resource.ttl 
 * @author Auto-generated by schemagen on 14 Jan 2015 09:40 
 */
public class Omn_resource {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://open-multinet.info/ontology/omn-resource#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "2014-12-7";
    
    public static final ObjectProperty requiredBy = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-resource#requiredBy" );
    
    public static final ObjectProperty requires = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-resource#requires" );
    
    /** <p>todo: omn-resource:NetworkObject or omn:Component??</p> */
    public static final OntClass Interface = m_model.createClass( "http://open-multinet.info/ontology/omn-resource#Interface" );
    
    /** <p>todo: still to decide if also at this level there is an equivalence to nml 
     *  concepts with the same name</p>
     */
    public static final OntClass Link = m_model.createClass( "http://open-multinet.info/ontology/omn-resource#Link" );
    
    /** <p>example: ports, paths, links, node, physical machine,machine, VM</p> */
    public static final OntClass NetworkObject = m_model.createClass( "http://open-multinet.info/ontology/omn-resource#NetworkObject" );
    
    /** <p>todo: still to decide if also at this level there is an equivalence to nml 
     *  concepts with the same name</p>
     */
    public static final OntClass Node = m_model.createClass( "http://open-multinet.info/ontology/omn-resource#Node" );
    
}
