/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import com.hp.hpl.jena.rdf.model.*;
import com.hp.hpl.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/willner/repositories/github/openmultinet/playground-rspecs-ontology/src/main/resources/omn-lifecycle.ttl 
 * @author Auto-generated by schemagen on 15 Jan 2015 09:04 
 */
public class Omn_lifecycle {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://open-multinet.info/ontology/omn-lifecycle#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>The ontology's owl:versionInfo as a string</p> */
    public static final String VERSION_INFO = "2015-01-15";
    
    public static final ObjectProperty implementedBy = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-lifecycle#implementedBy" );
    
    public static final ObjectProperty implements_ = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-lifecycle#implements" );
    
    public static final ObjectProperty parentOf = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-lifecycle#parentOf" );
    
    public static final ObjectProperty parentTo = m_model.createObjectProperty( "http://open-multinet.info/ontology/omn-lifecycle#parentTo" );
    
    /** <p>A collection (group) of resources/services/groups confirmed to be allocated 
     *  for the user.</p>
     */
    public static final OntClass Confirmation = m_model.createClass( "http://open-multinet.info/ontology/omn-lifecycle#Confirmation" );
    
    /** <p>A collection (group) of resources/services/groups allocated for the user.</p> */
    public static final OntClass Manifest = m_model.createClass( "http://open-multinet.info/ontology/omn-lifecycle#Manifest" );
    
    /** <p>A collection (group) of services and resources provided by an Infrastructure. 
     *  The collection is the result of the application of Policies.</p>
     */
    public static final OntClass Offering = m_model.createClass( "http://open-multinet.info/ontology/omn-lifecycle#Offering" );
    
    /** <p>A collection (group) of resources/services/groups requested by the user</p> */
    public static final OntClass Request = m_model.createClass( "http://open-multinet.info/ontology/omn-lifecycle#Request" );
    
    /** <p>The current state of the resource</p> */
    public static final OntClass State = m_model.createClass( "http://open-multinet.info/ontology/omn-lifecycle#State" );
    
}
